name: Build Kirin 970 Kernel
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 11 1/14 * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "2G"
      CCACHE_HARDLINK: "true"
      KERNEL_CMDLINE: "ARCH=arm64 CROSS_COMPILE=aarch64-none-linux-gnu- O=out"
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 1

    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Install dependencies
      run: |
        sudo apt-get update -y 
        sudo apt install binutils make python2 git git-lfs bc build-essential ccache curl lib32ncurses5-dev libncurses5 libncurses5-dev -y
        # git clone https://github.com/ibnudz/aarch64-linux-android-4.9 $(pwd)/toolchain
        git clone https://github.com/HoleHolo/ToolChains.git --depth=1 -b main
    
    - name: Get Time
      id: get_time
      run: |
        echo "TIME=$(TZ=UTC-8 date +%Y%m%d )" >> $GITHUB_OUTPUT

    - name: Build Kernel
      run: |
       sudo ln -sf /usr/bin/python2.7 /usr/bin/python
 
       if [ -d include/config ];
        then
         echo "Find config,will remove it"
         rm -rf include/config
       else
        echo "No Config,good."
       fi

       rm -rf KernelSU
       rm -rf drivers/kernelsu
       curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

       export PATH=$(pwd)/toolchain/bin/:$PATH
       export ARCH=arm64
       export SUBARCH=arm64
       make $KERNEL_CMDLINE merge_kirin970_defconfig
       make $KERNEL_CMDLINE -j$(nproc --all)
       tools/mkbootimg --kernel out/arch/arm64/boot/Image.gz --base 0x0 --cmdline "loglevel=4 initcall_debug=n page_tracker=on unmovable_isolate1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=permissive buildvariant=user" --tags_offset 0x07A00000 --kernel_offset 0x00080000 --ramdisk_offset 0x07C00000 --header_version 1 --os_version 9 --os_patch_level 2019-05-05  --output kernel-${{ steps.get_time.outputs.TIME }}-permissive.img
       tools/mkbootimg --kernel out/arch/arm64/boot/Image.gz --base 0x0 --cmdline "loglevel=4 initcall_debug=n page_tracker=on unmovable_isolate1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=enforcing buildvariant=user" --tags_offset 0x07A00000 --kernel_offset 0x00080000 --ramdisk_offset 0x07C00000 --header_version 1 --os_version 9 --os_patch_level 2019-05-05  --output kernel-${{ steps.get_time.outputs.TIME }}-enforcing.img

    - name: Upload Kernel
      uses: actions/upload-artifact@v3
      with:
        name: kirin-970-kernel-${{ steps.get_time.outputs.TIME }}
        path: "kernel-*.img"
